=== City4AgeProject/anagraph/backend/C4A/src/test/resources/db_test_data/xsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="testtest">
	<xsd:import namespace="testtest" schemaLocation="testtest.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="activity" type="dflt:activity__type" />
				<xsd:element name="cd_frailty_status" type="dflt:cd_frailty_status__type" />
				<xsd:element name="cd_detection_variable_type" type="dflt:cd_detection_variable_type__type" />
				<xsd:element name="variation_measure_value" type="dflt:variation_measure_value__type" />
				<xsd:element name="cd_role" type="dflt:cd_role__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="time_interval" type="dflt:time_interval__type" />
				<xsd:element name="frailty_status_timeline" type="dflt:frailty_status_timeline__type" />
				<xsd:element name="eam" type="dflt:eam__type" />
				<xsd:element name="assessment" type="dflt:assessment__type" />
				<xsd:element name="user_in_system" type="dflt:user_in_system__type" />
				<xsd:element name="inter_activity_behaviour_variation" type="dflt:inter_activity_behaviour_variation__type" />
				<xsd:element name="care_profile" type="dflt:care_profile__type" />
				<xsd:element name="action" type="dflt:action__type" />
				<xsd:element name="cd_typical_period" type="dflt:cd_typical_period__type" />
				<xsd:element name="user_in_role" type="dflt:user_in_role__type" />
				<xsd:element name="geriatric_factor_value" type="dflt:geriatric_factor_value__type" />
				<xsd:element name="pilot" type="dflt:pilot__type" />
				<xsd:element name="assessed_gef_value_set" type="dflt:assessed_gef_value_set__type" />
				<xsd:element name="cr_profile" type="dflt:cr_profile__type" />
				<xsd:element name="source_evidence" type="dflt:source_evidence__type" />
				<xsd:element name="cd_data_source_type" type="dflt:cd_data_source_type__type" />
				<xsd:element name="executed_action" type="dflt:executed_action__type" />
				<xsd:element name="numeric_indicator_value" type="dflt:numeric_indicator_value__type" />
				<xsd:element name="cd_pilot_detection_variable" type="dflt:cd_pilot_detection_variable__type" />
				<xsd:element name="cd_detection_variable" type="dflt:cd_detection_variable__type" />
				<xsd:element name="location" type="dflt:location__type" />
				<xsd:element name="assessment_audience_role" type="dflt:assessment_audience_role__type" />
				<xsd:any namespace="testtest" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== City4AgeProject/anagraph/backend/C4A/src/test/resources/ExternalDAOTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="db_test_data/xsd/dataset.xsd">

	<cd_detection_variable id="1" detection_variable_type="OVL" derived_detection_variable_id="2"/>
	<cd_detection_variable id="2" detection_variable_type="GFG" detection_variable_name="GFG name" />
	<cd_detection_variable id="3" detection_variable_type="GFG"/>
	<cd_detection_variable id="4" detection_variable_type="GFG"/>
	<cd_detection_variable id="5" detection_variable_type="GEF"/>
	<cd_detection_variable id="6" detection_variable_type="GEF"/>
	<cd_detection_variable id="7" detection_variable_type="GEF"/>
	
	<cd_detection_variable_type detection_variable_type="OVL" />
	<cd_detection_variable_type detection_variable_type="GFG" />
	<cd_detection_variable_type detection_variable_type="GEF" />
	
	<geriatric_factor_value id="1" gef_type_id="1" user_in_role_id="1"/>
	<geriatric_factor_value id="2" gef_type_id="2" user_in_role_id="1"/>
	<geriatric_factor_value id="3" gef_type_id="3" user_in_role_id="1"/>
	<geriatric_factor_value id="4" gef_type_id="4" user_in_role_id="1"/>
	<geriatric_factor_value id="5" gef_type_id="5" user_in_role_id="1"/>
	<geriatric_factor_value id="6" gef_type_id="6" user_in_role_id="1"/>
	<geriatric_factor_value id="7" gef_type_id="7" user_in_role_id="1"/>
	<geriatric_factor_value id="8" gef_type_id="1" user_in_role_id="1"/>
	<geriatric_factor_value id="9" gef_type_id="1" user_in_role_id="1"/>
	
	<user_in_role id="1" user_in_system_id="1"/>
	
	<user_in_system id="1" username="ivica"/>
     
</dataset>

=== City4AgeProject/anagraph/backend/C4A/src/test/resources/AssessmentDAOTest.getDiagramDataForUserInRoleIdAndParentId.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="db_test_data/xsd/dataset.xsd">

    <geriatric_factor_value id="1" gef_value="5" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="2" gef_value="3.9" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="3" gef_value="3.3" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="4" gef_value="2.5" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="5" gef_value="3.9" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    <geriatric_factor_value id="6" gef_value="4.1" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="7" gef_value="3" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="8" gef_value="3.1" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="9" gef_value="3" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="10" gef_value="2.8" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    <geriatric_factor_value id="11" gef_value="5" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="12" gef_value="3.9" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="13" gef_value="3.3" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="14" gef_value="2.5" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="15" gef_value="3.9" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    <geriatric_factor_value id="16" gef_value="4.1" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="17" gef_value="3" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="18" gef_value="3.1" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="19" gef_value="3" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="20" gef_value="2.8" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    <geriatric_factor_value id="21" gef_value="5" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="22" gef_value="3.9" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="23" gef_value="3.3" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="24" gef_value="2.5" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="25" gef_value="3.9" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    <geriatric_factor_value id="26" gef_value="4.1" time_interval_id="1" user_in_role_id="1" gef_type_id="2" />
    <geriatric_factor_value id="27" gef_value="3" time_interval_id="2" user_in_role_id="1" gef_type_id="3" />
    <geriatric_factor_value id="28" gef_value="3.1" time_interval_id="3" user_in_role_id="1" gef_type_id="4" />
    <geriatric_factor_value id="29" gef_value="3" time_interval_id="4" user_in_role_id="1" gef_type_id="5" />
    <geriatric_factor_value id="30" gef_value="2.8" time_interval_id="5" user_in_role_id="1" gef_type_id="6" />
    
    <time_interval id="1" interval_start="2016-01-01 00:00:00" interval_end="2016-02-01 00:00:00" typical_period="1" />
    <time_interval id="2" interval_start="2016-02-01 00:00:00" interval_end="2016-03-01 00:00:00" typical_period="1" />
    <time_interval id="3" interval_start="2016-03-01 00:00:00" interval_end="2016-04-01 00:00:00" typical_period="1" />
    <time_interval id="4" interval_start="2016-04-01 00:00:00" interval_end="2016-05-01 00:00:00" typical_period="1" />
    <time_interval id="5" interval_start="2016-05-01 00:00:00" interval_end="2016-06-01 00:00:00" typical_period="1" />
    
    <cd_typical_period typical_period="1" period_description="month" />
    
    <cd_detection_variable id="1" detection_variable_name="Motility" detection_variable_type="GEF" />
    <cd_detection_variable id="2" detection_variable_name="Walking" detection_variable_type="GES" derived_detection_variable_id="1"  />
    <cd_detection_variable id="3" detection_variable_name="Climbing stairs" detection_variable_type="GES" derived_detection_variable_id="1" />
    <cd_detection_variable id="4" detection_variable_name="Still/Moving" detection_variable_type="GES" derived_detection_variable_id="1" />
    <cd_detection_variable id="5" detection_variable_name="Moving across rooms" detection_variable_type="GES" derived_detection_variable_id="1" />
    <cd_detection_variable id="6" detection_variable_name="Gait balance" detection_variable_type="GES" derived_detection_variable_id="1" />
    
    <cd_pilot_detection_variable pilot_id="1" detection_variable_id="2" detection_variable_description_formula="Desc 1" />
    <cd_pilot_detection_variable pilot_id="1" detection_variable_id="3" detection_variable_description_formula="Desc 2" />
    <cd_pilot_detection_variable pilot_id="1" detection_variable_id="4" detection_variable_description_formula="Desc 3" />
    <cd_pilot_detection_variable pilot_id="1" detection_variable_id="5" detection_variable_description_formula="Desc 4" />
    <cd_pilot_detection_variable pilot_id="1" detection_variable_id="6" detection_variable_description_formula="Desc 5" />
    
    <pilot id="1" name="Test" population_size="500" />
    
    <assessment id="1" />
    <assessment id="2" />
    <assessment id="3" />
    <assessment id="4" />
    <assessment id="5" />
    
    <assessed_gef_value_set assessment_id="1" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="2" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="2" gef_value_id="2" />
    <assessed_gef_value_set assessment_id="2" gef_value_id="3" />
    <assessed_gef_value_set assessment_id="3" gef_value_id="3" />
    
    <assessment_audience_role assessment_id="1" role_id="1" />
    <assessment_audience_role assessment_id="1" role_id="2" />
    <assessment_audience_role assessment_id="1" role_id="3" />
    <assessment_audience_role assessment_id="2" role_id="3" />
    <assessment_audience_role assessment_id="2" role_id="4" />
    <assessment_audience_role assessment_id="3" role_id="4" />
    <assessment_audience_role assessment_id="4" role_id="4" />
    
    <user_in_role id="1" />
    <user_in_role id="2" />
    <user_in_role id="3" />
    
</dataset>

=== City4AgeProject/anagraph/backend/C4A/src/test/resources/AssessmentDAOTest.getAssessmentsForSelectedDataSet.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="db_test_data/xsd/dataset.xsd">

    <geriatric_factor_value id="1" gef_value="5" user_in_role_id="1" />
    <geriatric_factor_value id="2" gef_value="3.9" user_in_role_id="1" />
    <geriatric_factor_value id="7" gef_value="3" user_in_role_id="1" />
 
    <assessment id="184" author_id="1" />
    <assessment id="185" author_id="2" />
    <assessment id="187" author_id="1" />
    <assessment id="191" author_id="1" />
    
    <assessment id="196" author_id="2" />
    
    <assessment id="190" author_id="2" />
    
    <assessed_gef_value_set assessment_id="184" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="185" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="187" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="191" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="184" gef_value_id="2" />
    <assessed_gef_value_set assessment_id="185" gef_value_id="2" />
    <assessed_gef_value_set assessment_id="187" gef_value_id="2" />
    <assessed_gef_value_set assessment_id="191" gef_value_id="2" />
    
    <assessed_gef_value_set assessment_id="196" gef_value_id="1" />
    <assessed_gef_value_set assessment_id="196" gef_value_id="2" />
    
    <assessed_gef_value_set assessment_id="190" gef_value_id="7" />
    
    <assessment_audience_role assessment_id="184" role_id="1" />
    <assessment_audience_role assessment_id="184" role_id="2" />
    <assessment_audience_role assessment_id="185" role_id="1" />
    <assessment_audience_role assessment_id="185" role_id="2" />
    <assessment_audience_role assessment_id="187" role_id="1" />
    <assessment_audience_role assessment_id="187" role_id="2" />
    <assessment_audience_role assessment_id="191" role_id="1" />
    <assessment_audience_role assessment_id="191" role_id="2" />
    
    <assessment_audience_role assessment_id="196" role_id="1" />
    <assessment_audience_role assessment_id="196" role_id="2" />
    
    <assessment_audience_role assessment_id="190" role_id="7" />
    
    <cd_role id="1" />
    <cd_role id="2" />
    <cd_role id="7" />
    
    <user_in_role id="1" user_in_system_id="1" />
    <user_in_role id="2" user_in_system_id="2" />
    <user_in_role id="7" user_in_system_id="3" />
    
    <user_in_system id="1" />
    <user_in_system id="2" />
    <user_in_system id="3" />
    
</dataset>

=== City4AgeProject/anagraph/backend/C4A/src/test/resources/ExternalDAOTest2.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="db_test_data/xsd/dataset.xsd">

	<user_in_role id="1" role_id="1" user_in_system_id="1" />
	<user_in_role id="2" role_id="1" />
	<user_in_role id="3" role_id="1" />
	<user_in_role id="4" role_id="1" />
	<user_in_role id="5" role_id="1" />
	<user_in_role id="6" role_id="1" />
	<user_in_role id="7" role_id="1" />
	
	<cd_role id="1" />
	
	<frailty_status_timeline user_in_role_id="1" time_interval_id="1" changed_by="1" changed="2015-01-01 00:00:00" frailty_status="XXX" />
	
	<time_interval id="1" />
	
	<cr_profile id="1" user_in_role_id="1" gender="true" />
	<cr_profile id="2" user_in_role_id="1" gender="false" />
	<cr_profile id="3" user_in_role_id="1" gender="true" />
	
	<care_profile user_in_role_id="1" />
	
	<user_in_system id="1" username="admin" />
	
	<cd_frailty_status frailty_status="XXX" />
	
</dataset>
